### ISSUE TITLE
Can't build base64 using Stack with GHC 8.2.2

### ISSUE THREAD

**Issue by vaibhavsagar** [emilypi/base64#4]
I'm trying to switch one of my projects over to use `base64` instead of `base64-bytestring`, and I'm getting this output with the latest Stack and an `lts-11` resolver (GHC 8.2.2):

```
base64                 > Configuring base64-0.3.0.0...
base64                 > setup: This package description follows version 2.4 of the Cabal
base64                 > specification. This tool only supports up to version 2.0.1.1.
```

You can see this output [here](https://travis-ci.org/vaibhavsagar/duffer/builds/634425405).

Is this not a supported combination of compiler + build tool?

**Comment by emilypi** [comment]
Does stack not support cabal 2.4? That's ridiculous - It's been out for years! Apparently it doesn't because I can confirm it on my end - it's a stack problem. Either way, I'll drop the cabal version down to 2 for compat with the next release. I'll have it out on Friday after a quick discussion with Carter about some features I'm adding.

**Comment by emilypi** [comment]
@vaibhavsagar dropped the cabal version so Stack can build the project in 0.3.1
