### ISSUE TITLE
base64 vs. base64url are not disambiguated sufficiently

### ISSUE THREAD

**Issue by leftaroundabout** [emilypi/base64#44]
The [`Base64`](https://hackage.haskell.org/package/base64-0.4.2.4/docs/Data-ByteString-Base64.html) and [`Base64.URL`](https://hackage.haskell.org/package/base64-0.4.2.4/docs/Data-ByteString-Base64-URL.html) modules both contain functions called `encodeBase64`, `decodeBase64` etc.. This [causes confusion](https://stackoverflow.com/questions/72727879/different-utf8-encoding-outputs-between-python-and-haskell) at the expectation that `encodeBase64` should be compatible with e.g. Python's `b64encode`. It is also somewhat at odds with [the standard's recommendation](https://datatracker.ietf.org/doc/html/rfc4648#section-5)

> This encoding may be referred to as "base64url".  This encoding should not be regarded as the same as the "base64" encoding and
   should not be referred to as only "base64".  Unless clarified otherwise, "base64" refers to the base 64 in the previous section.

Arguably, the fact that it's in a module with `URL` in the name is sufficient clarification. However, if we're going to rely on the module name / qualified imports, then the functions might as well just be called `encode` and `decode`, without even mentioning that it's base64.

**Comment by emilypi** [comment]
In a recent [RFC](https://www.reddit.com/r/haskell/comments/tx4aop/rfc_upcoming_changes_to_the_base64_library/), the disambiguation you speak of will be made concrete at the typelevel, as well as in the module name. It's currently in `master` and waiting for release this summer, along with some performance improvements. 

> Arguably, the fact that it's in a module with URL in the name is sufficient clarification. 

Qualification was the intent in previous iterations, which makes sense to sufficiently disambiguate the API. And to be fair, this kind of API distinction is idiomatic Haskell. You really can't help the user in the stackoverflow question with an api change, due to their ignorance of the encoding format. Even if I had named it `encodeBase64Url`, they would have made the same mistake, because they didn't know what they were doing and what alphabets were being used in either the Python or the Haskell case!

> However, if we're going to rely on the module name / qualified imports, then the functions might as well just be called encode and decode, without even mentioning that it's base64.

Disagree. `encode/decode` is not sufficient to know what the function is doing if a poor qualification name like `STD` or `URL` is chosen. `STD.encode` and `URL.encode` give no information about the encoding type unless you choose to embed some reference to the fact that it's a base64 encoding in the provenance of the name, which means you're gonna be typing `b64` or `base64` for a qualified name anyway. The fact that `encode` is so overloaded in haskell is the main problem here. There are a [ridiculous](https://hoogle.haskell.org/?hoogle=encode) number of `encode` functions  and little to no easy way to disambiguate them aside from cleverly chosen qualified name. 

An easy way to mitigate all of this is just making sure the function name contains the encoding information. tl;dr you win a little but not much in either case, and at this point, I'd rather not completely rewrite the package, considering typing 6 characters is really not gonna break the camel's back.

**Comment by emilypi** [comment]
Great question tho! Still, closing the issue cuz it's a bikeshed.
